export type {Comment, CommentSchema} from "./model/types/comments"
export {ValidateCommentError} from "./model/types/comments"
export {commentsReducer, getCommentsData} from "./model/slice/commentsSlice"
export {getCommentsLoading, getCommentsError} from "./model/selectors/getComments"
export {CommentSkeleton} from "./ui/comment-skeleton/CommentSkeleton"
export {CommentList} from "./ui/comment-list/CommentList"
