export {ArticleDetailsCard} from "./ui/ArticleDetailsCard"
export type {Article} from "./model/types/article"
export type {ArticleSchema} from "./model/types/articleSchema"
export {articleSlice, articleReducer, articleActions} from "./model/slice/articleSlice"
export {getArticleData, getArticleLoading, getArticleError} from "./model/selectors/getArticleDetails"
