export enum ValidateProfileError {
    INCORRECT_USER_DATA = "INCORRECT_USER_DATA",
    INCORRECT_EMAIL = "INCORRECT_EMAIL",
    INCORRECT_PHONE = "INCORRECT_PHONE",
    NO_DATA = "NO_DATA",
    SERVER_ERROR = "SERVER_ERROR"
}
