export type PositionType = "top" | "right" | "left" | "bottom"
export type DirectionType = "row" | "column"
export type AlignType = "left" | "center" | "right"
export type UIFeatureType = "blank" | "inverted"
export type SizeType = "xs" | "sm" | "md" | "lg" | "xl" | "xxl" | "auto" | "none"
