name: GitHub Actions (linting, testing, building)
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Project_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}...
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules...
        run: npm i
      - name: Building Production project...
        run: npm run build:prod
      - name: Linting Production project... [typescript]
        run: npm run lint:ts
      - name: Linting Production project... [styles]
        run: npm run lint:css
      - name: Testing Production project...
        run: npm run test:unit
      - name: Building Production project... [storybook]
        run: npm run storybook:build
      - name: Testing Production project... [screenshots]
        run: npm run test:ui:ci
